### PR TITLE
fix module.exports

### PR DESCRIPTION
**Pull request by vvo**

### CODE REVIEW

**Comment by vvo** [comment]
@ded ?

**Comment by ded** [comment]
hmmm... not a bad change, but it will introduce breakage for anyone using this library. we'll have to introduce it in another major release

**Comment by vvo** [comment]
@ded What about now? see 63591da04cf3d2cf25178ebebe1f8b72a88aa758

**Comment by vvo** [comment]
We can close this right? thx

**Comment by ded** [comment]
:+1:

**Pull request closed without merging**
