### PR TITLE
add ios9 ua

### PR DESCRIPTION
**Pull request by orcaman**
iOS 9 was not detected, I added a user agent according to what I'm detecting on my phone.

### CODE REVIEW

**Comment by MoOx** [comment]
> +966 −956 

Why ?

**Comment by vielmetti** [comment]
"SyntaxError: Unexpected token" in Travis build

**Comment by bjankord** [comment]
Looks like more was done than adding detection for iOS9.

**Comment by ded** [comment]
@orcaman Thanks for your change! Looks like you altered the style - Would you mind updating the request to match the existing coding style?

**Comment by lancedikson** [comment]
@orcaman ping

**Comment by orcaman** [comment]
@lancedikson slipped my mind. I'm closing this PR and creating a new one

**Pull request closed without merging**
