### PR TITLE
rebuild master

### PR DESCRIPTION
**Pull request by rmosolgo**
Hi, I wanted desktop OS detection but I didn't see it in `bowser.js`. Here are some rebuilt versions. 

Maybe you don't want to distribute the code this way, that's fine, you can just close this PR!

Thanks for the great library!

### CODE REVIEW

**Comment by mlanin** [comment]
+1 update please built version

**Comment by lancedikson** [comment]
Already in master

**Comment by mlanin** [comment]
@lancedikson but still not in release?

**Comment by lancedikson** [comment]
@mlanin, not in release, as I know. I'm preparing a next minor release in a few days.

**Pull request closed without merging**
