### PR TITLE
add ios9

### PR DESCRIPTION
**Pull request by orcaman**

### CODE REVIEW

**Comment by orcaman** [comment]
hmm.. seems like the build fails. it doesn't like the fact that I'm  calling the version 9.0.0 (expects 9.0).

Also it says it's not expecting "version", but I only have "osversion" - any idea?

**Comment by lancedikson** [comment]
@orcaman, ok, looks like the script wanna see something like that: `iPhone OS 9_0_0`. Is it a real UA? I mean, have you ever seen UA that contains `iPhone OS 9_0` (with only a zero)? And of course, the `version` property will contain `9.0` because of your UA has `Version/9.0` substring.

However, we are thinking to change iOS browser detection in future, look at #111 for information.

**Comment by orcaman** [comment]
@lancedikson yup, my iPhone reported that at a certain point, and I found it [here](https://user-agents.me/useragent/mozilla50-iphone-cpu-iphone-os-9_0-like-mac-os-x-applewebkit601146-khtml-like-gecko-version90-mobile13a344-safari6011) as well. 

Regarding the future plans for iOS detection, what do you suggest? I don't mind closing the PR if you think it's the way to go, however I can tell you that in my case if it weren't for this commit I wouldn't be able to use bowser.

**Comment by lancedikson** [comment]
@orcaman, I got it. There is a simple solution of the problem: in cases like you have sent with `iPhone OS 9_0` in UA bowser's result would contain the `version` property with a value `9.0` (not `9.0.0`). And this is the most suitable solution as I think. If you are agree with me, don't close it, I'm merging it for the next minor release. Anyway you can suggest another solution :)

Future plans are to detect the real browser name and version on iOS devices. Now as you know name of the browser is a kind of iOS device (iPhone, iPod, iPad), but would be better a real browser name (Safari, Chrome, Opera Coast, etc). But don't think about that right now, it's just a feature request that discussed in #111.

**Comment by orcaman** [comment]
@lancedikson sounds good. I'll make the change

**Pull request closed without merging**
